name: gltf_loader
description: "Pure dart glTF 2.0 Specification loader utility with dynamic asset loading"
version: 0.3.0
repository: https://github.com/rusoleal/dart-3d-tools
topics:
  - gltf
  - flutter3d
  - model3d
funding:
  - https://buymeacoffee.com/rusoleal
  - https://github.com/sponsors/rusoleal

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
